In [1]:
import numpy as np

In [2]:
def gs(A, B, iters=10000, λ = 0.2):
    X = np.zeros(A.shape[1])
    bk = np.zeros(A.shape[1])
    for it in range(iters):
        for i in range(A.shape[1]):
            X[i] = B[i]
            for j in range(A.shape[1]):
                if j == i:
                    continue
                X[i] -= A[i,j]*X[j]
            X[i] /= A[i,i]

            X[i] = λ*X[i] + (1 - λ)*X[i]
        if np.array_equal(bk,X):
            print(it)
            return X

        bk = np.copy(X)  
    return X

In [3]:
def jacobi(A, B, iters=10000, λ = 0.2):
    X = np.zeros(A.shape[1])
    X_temp = np.zeros(A.shape[1])
    bk = np.zeros(A.shape[1])
    for it in range(iters):
        for i in range(A.shape[1]):
            X_temp[i] = B[i]
            for j in range(A.shape[1]):
                if j == i:
                    continue
                X_temp[i] -= A[i,j]*X[j]
            X_temp[i] /= A[i,i]

            X_temp[i] = λ*X_temp[i] + (1 - λ)*-X_temp[i]
            
        X = np.copy(X_temp)
        if np.array_equal(bk,X):
            print(it)
            return X

        bk = np.copy(X)  
    return X

In [4]:
A = np.array([[3, -0.1, -0.2] , [0.1, 7, -0.3] , [0.3, -0.2, 10]])
#A = np.array([[1, 1/2, 1/3] , [1, 2/3, 1/2] , [1, 3/4, 3/5]])
print(A)

[[  3.   -0.1  -0.2]
 [  0.1   7.   -0.3]
 [  0.3  -0.2  10. ]]


In [5]:
B = np.array([[7.85] , [-19.3] , [71.4]])
#B = np.array([[1.833333] , [2.166667] , [2.35]])
print(B)

[[  7.85]
 [-19.3 ]
 [ 71.4 ]]


In [6]:
print('Gauss-Seidel',gs(A, B, λ = 0))
print('Jacobi',jacobi(A, B, λ = 0))

9
Gauss-Seidel [ 3.  -2.5  7. ]
13
Jacobi [-2.2333747   3.03671188 -7.26773548]
